-- MySQL Script generated by MySQL Workbench
-- Fri Jan 10 23:14:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jnk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jnk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jnk` DEFAULT CHARACTER SET utf8 ;
USE `jnk` ;

-- -----------------------------------------------------
-- Table `jnk`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jnk`.`place` (
  `place_id` INT NOT NULL,
  `place_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`place_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jnk`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jnk`.`type` (
  `type_id` INT NOT NULL,
  `type_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jnk`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jnk`.`device` (
  `device_id` INT NOT NULL,
  `device_name` VARCHAR(50) NOT NULL,
  `device_place_id` INT NOT NULL,
  `device_type_id` INT NOT NULL,
  `device_refillable` TINYINT NOT NULL DEFAULT 0 COMMENT 'bool 0-Falce/1-True \nTrue - if the device has a part',
  PRIMARY KEY (`device_id`),
  INDEX `my_type_idx` (`device_id` ASC, `device_type_id` ASC) VISIBLE,
  INDEX `my_place_idx` (`device_place_id` ASC) INVISIBLE,
  INDEX `my_type_idx1` (`device_type_id` ASC) VISIBLE,
  CONSTRAINT `my_place`
    FOREIGN KEY (`device_place_id`)
    REFERENCES `jnk`.`place` (`place_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `my_type`
    FOREIGN KEY (`device_type_id`)
    REFERENCES `jnk`.`type` (`type_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jnk`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jnk`.`manufacturer` (
  `manufacturer_id` INT NOT NULL,
  `manufacturer_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`manufacturer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jnk`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jnk`.`model` (
  `model_id` INT NOT NULL,
  `model_name` VARCHAR(50) NOT NULL,
  `model_manufacturer_id` INT NOT NULL,
  `model_type_id` INT NOT NULL,
  PRIMARY KEY (`model_id`),
  INDEX `my_manufacturer_id_idx` (`model_manufacturer_id` ASC) VISIBLE,
  INDEX `my_type_id_idx` (`model_type_id` ASC) VISIBLE,
  CONSTRAINT `my_manufacturer_id`
    FOREIGN KEY (`model_manufacturer_id`)
    REFERENCES `jnk`.`manufacturer` (`manufacturer_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `my_type_id`
    FOREIGN KEY (`model_type_id`)
    REFERENCES `jnk`.`type` (`type_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jnk`.`param`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jnk`.`param` (
  `param_id` INT NOT NULL,
  `param_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`param_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jnk`.`default_type_param_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jnk`.`default_type_param_list` (
  `param_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  UNIQUE INDEX `parameter_id_UNIQUE` (`param_id` ASC) VISIBLE,
  UNIQUE INDEX `type_id_UNIQUE` (`type_id` ASC) VISIBLE,
  CONSTRAINT `my_type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `jnk`.`type` (`type_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `my_param_id`
    FOREIGN KEY (`param_id`)
    REFERENCES `jnk`.`param` (`param_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jnk`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jnk`.`history` (
  `history_id` INT NOT NULL,
  `history_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `history_text` VARCHAR(200) NOT NULL,
  `history_device_id` INT NOT NULL,
  PRIMARY KEY (`history_id`),
  INDEX `my_device_id_idx` (`history_device_id` ASC) VISIBLE,
  CONSTRAINT `my_device_id`
    FOREIGN KEY (`history_device_id`)
    REFERENCES `jnk`.`device` (`device_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jnk`.`service_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jnk`.`service_date` (
  `service_date_id` INT NOT NULL,
  `service_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `service_date_text` VARCHAR(200) NOT NULL,
  `service_date_device_id` INT NOT NULL,
  PRIMARY KEY (`service_date_id`),
  INDEX `my_device_id_idx` (`service_date_device_id` ASC) VISIBLE,
  CONSTRAINT `my_device_id`
    FOREIGN KEY (`service_date_device_id`)
    REFERENCES `jnk`.`device` (`device_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
